# TODO: bake custom image with suite
default:
  image: ubuntu:22.04

  before_script:
    - apt update
    - apt install -y bsdmainutils curl make       # bsdmainutils for 'hexdump'
    - curl -LO https://github.com/YosysHQ/oss-cad-suite-build/releases/download/2022-05-20/oss-cad-suite-linux-x64-20220520.tgz
    - curl -LO https://github.com/xpack-dev-tools/riscv-none-embed-gcc-xpack/releases/download/v10.2.0-1.2/xpack-riscv-none-embed-gcc-10.2.0-1.2-linux-x64.tar.gz
    - tar xfa oss-cad-suite-linux-x64-20220520.tgz
    - tar xfa xpack-riscv-none-embed-gcc-10.2.0-1.2-linux-x64.tar.gz
    - export PATH=`pwd`/oss-cad-suite/bin:$PATH
    - export PATH=`pwd`/xpack-riscv-none-embed-gcc-10.2.0-1.2/bin:$PATH
    - echo $PATH

build_ulx3s:
  stage: build
  needs: []

  script:
    - make -C boot
    - make ulx3s.bit

  artifacts:
    paths:
      - boot/boot.elf
      - ulx3s.bit
      - "*.log"

test_cocotb:
  stage: test
  needs: []

  script:
    - make -C boot
    - make -f Makefile.coco

  artifacts:
    paths:
      - boot/boot.elf
      - "*.vcd"
