stages:
  - build
  - test
  - upload


default:
  image: mcejp/poly94-buildenv:latest

  # Backup, to be used with ubuntu:20.04
  # before_script:
  #   - apt update
  #   - apt install -y bsdmainutils curl make       # bsdmainutils for 'hexdump'
  #   - curl -sL https://github.com/YosysHQ/oss-cad-suite-build/releases/download/2022-05-20/oss-cad-suite-linux-x64-20220520.tgz | tar xz
  #   - curl -sL https://github.com/xpack-dev-tools/riscv-none-embed-gcc-xpack/releases/download/v10.2.0-1.2/xpack-riscv-none-embed-gcc-10.2.0-1.2-linux-x64.tar.gz | tar xz
  #   - export PATH=`pwd`/oss-cad-suite/bin:`pwd`/xpack-riscv-none-embed-gcc-10.2.0-1.2/bin:$PATH
  #   - echo $PATH


variables:
  GIT_SUBMODULE_STRATEGY: recursive


build_ulx3s:
  stage: build
  needs: []

  script:
    - cmake -DCMAKE_TOOLCHAIN_FILE=../toolchain.cmake -DCMAKE_BUILD_TYPE=MinSizeRel -S boot -B boot/build
    - cmake --build boot/build --target boot
    - make ulx3s.bit

  artifacts:
    paths:
      - boot/boot.elf
      - build/nextpnr-report.json
      - ulx3s.bit
      - "*.log"
    when: always


test_cocotb:
  stage: test
  needs: []

  script:
    - cmake -DCMAKE_TOOLCHAIN_FILE=../toolchain.cmake -DCMAKE_BUILD_TYPE=MinSizeRel -S boot -B boot/build
    - cmake --build boot/build --target boot
    - make -f Makefile.coco
    - "! grep -q '<failure' results.xml"

  artifacts:
    paths:
      - boot/boot.elf
      - "*.vcd"
      - "results.xml"
    when: always
    reports:
      junit: results.xml


test_verilator:
  stage: test
  needs: []

  script:
    - cmake -DCMAKE_TOOLCHAIN_FILE=../toolchain.cmake -DCMAKE_BUILD_TYPE=MinSizeRel -S boot -B boot/build
    - cmake --build boot/build --target boot_sdram test_dhrystone test_framebuffer
    - BOOTROM=boot/build/test_framebuffer.bin DUMP_FRAMEBUF=framebuffer.ppm NUM_CYCLES=4000000 make sim
    - if ! cmp -s framebuffer.ppm test_expected/test_framebuffer.ppm; then echo "Output not equal to expectation"; touch verilator.fail; exit 1; fi
    - BOOTROM=boot/build/boot_sdram.bin NUM_CYCLES=3000000 SDRAM_PRELOAD=boot/build/test_dhrystone.bin make sim | tee sim.log
    - sed -Ez 's/.*Dhrystones per Second:\s*([0-9]+).*/\1/g' sim.log > dhrystones_per_second
    - touch verilator.pass

  artifacts:
    paths:
      - dhrystones_per_second
      - framebuffer.ppm
      - verilator.fail
      - verilator.pass
    when: always


reports:
  stage: upload
  needs:
  - job: build_ulx3s
    artifacts: true
  - job: test_cocotb
    artifacts: true
  - job: test_verilator
    artifacts: true
  when: always

  image: python:3.10

  script:
    - pip install "psycopg>=3"
    - ./tools/ci/save_build_stats.py


pages:
  stage: upload
  needs: [reports]

  image: python:3.10

  script:
    - mkdir public
    - pip install Jinja2 "psycopg>=3"
    - ./tools/ci/present_build_stats.py > public/builds.html

  artifacts:
    paths:
    - public
